# Generated by Django 5.1.1 on 2024-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
